INSERT INTO CARDPACK_STORE
WITH WT1 AS (
  SELECT B.CARDPACK_ID, NVL(SUM(A.BACK_VIEW_CNT) + SUM(A.RIGHT_CNT)*2 + SUM(A.WRONG_CNT), 0) IDX FROM CARDPACKS B, STUDY_ACT_LOG A
  WHERE B.CARDPACK_ID = A.CARDPACK_ID(+)
  GROUP BY B.CARDPACK_ID
), WT2 AS (
  SELECT ROW_NUMBER() OVER (ORDER BY A.IDX DESC) RANK, A.IDX, A.CARDPACK_ID, B.CARDPACK_NAME TITLE FROM WT1 A, CARDPACKS B
  WHERE A.CARDPACK_ID = B.CARDPACK_ID
  AND B.CARDPACK_ACCESS_CD = 'pu'
)
SELECT RANK, CARDPACK_ID, TITLE FROM WT2